config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'



  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => { omniauth_callbacks: 'omniauth_callbacks'}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  constraints subdomain: 'ico' do
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
      scope module: 'ico', as: 'ico' do
        devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "ico/registrations" }
        devise_scope :ico_user do
          get 'sign_in', to: 'sessions#new', module: 'ico'
          delete 'sign_out', to: 'sessions#destroy', module: 'ico'
          get 'sign_up', to: 'registrations#new', module: 'ico'
        end
        root 'static_pages#ico_landing', module: 'ico'
        get 'static_pages/ico_landing'
        get 'static_pages/in_develop'
        get 'account', to: 'account#index'
        post 'account/add_eth'
        post 'kyc/create'
        resources :etz_investments
      end
      root 'static_pages#ico_landing', module: 'ico'
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
    root 'static_pages#ico_landing', module: 'ico'
  end
  root 'static_pages#home'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
    resources :profiles, except: [:edit, :destroy]
    resources :auctions, except: [:destroy]
    get 'my_profile', to: 'profiles#show', as: 'my_profile'
    get 'my_profile/edit', to: 'profiles#edit', as: 'edit_my_profile'
    get 'my_bids', to: 'auctions#my_bids', as: 'auctions_my_bids'
    get 'auctions/:id/videodate', to: 'auctions#videodate', as: 'auctions_videodate'
    resources :personal_messages, only: [:new,  :create]
    resources :conversations, only: [:index, :show]
    root 'static_pages#in_develop'
    get 'terms_of_use', to: 'static_pages#terms_of_use'
    get 'privacy_policy', to: 'static_pages#privacy_policy'
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" }
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
      get 'sign_up', to: 'devise/registrations#new'
    end
    resources :promos, except: [:edit, :destroy]
    post 'activate_promo', to: 'promos#activate'
    post 'payment', to: 'payments#payment'
    post 'payment_result', to: 'payments#payment_result'
    get 'payment', to: 'payments#payment_redirect'
    get 'payment_result', to: 'payments#payment_redirect'
  end
  post 'process_payment_result', to: 'payments#process_payment_result'
  get 'process_payment_result', to: 'payments#payment_redirect'
  resources :conversations, only: [:index]
end

app/controllers/ico/static_pages_controller.rb
class Ico::StaticPagesController < Ico::IcoController
  def ico_landing
  end
  def in_develop
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  layout "landing", only: ['home']
  def home
    redirect_to my_profile_path if user_signed_in?
  end

  def in_develop
  end

  def terms_of_use
  end

  def privacy_policy
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_privacy_policy.html.erb
<h1>Privacy Policy</h1>
<p>RateDate.net has created this privacy statement in order to demonstrate our commitment to privacy. The following discloses the information-gathering and dissemination practices for this web site.</p>
<h2>Information is Automatically Logged</h2>
<p>This site uses a visitor statistics package that logs the following information on each page access: userid, IP, host, browser type, computing platform, date and time, page viewed, referer, request type, and query_string. We use this information to help diagnose problems with our server and to administer our web site, and to help identify you. This information is also gathered because we like to see who is visiting.&nbsp;This information is not and will never be divulged to a third party unless required by law.</p>
<h2>Cookies</h2>
<p>This site uses cookies to deliver content specific to your interests, to save your password so you don't have to re-enter it each time you visit our site, and for other purposes.</p>
<h2>Registration Forms</h2>
<p>Our site's registration form requires users to give us contact information (i.e. email address). Contact information from the registration forms is used to validate the user's account. This enables the site administrators to provide moderation for the various public features of this site, and to get in touch with the user when necessary.&nbsp;This information is not and will never be divulged to a third party unless required by law.&nbsp;We use this data to tailor our visitor's experience at our site showing them content that we think they might be interested in, and displaying the content according to their preferences.</p>
<h2>External Links</h2>
<p>This site contains links to other sites. RateDate.net is not responsible for the privacy practices or the content of such web sites.</p>
<h2>Personal data</h2>
<p>Please remember that any information that is disclosed in this areas becomes public information and you should exercise caution when deciding to disclose your personal information. All postings are property of their respective author. Improper language is automatically censored by the system. All submissions are subject to our editorial control -- editorial changes will be indicated.</p>
<h2>Security</h2>
<p>This site has security measures in place to protect the loss, misuse, and alteration of the information under our control.</p>
<h2>Data Quality/Access</h2>
<p>This site gives users control over their user experience and content that they may have provided. Users can in some cases freely modify or delete any content they post for a limited time.</p>
<h2>Limitation of Liability</h2>
<p>RateDate.net is not liable for any damages caused by any of the site content, whether directly provided by RateDate.net its employees or not.</p>
<h2>Contacting the Web Site</h2>
<p>If you have any questions about this privacy statement, the practices of this site, or your dealings with this web site, you can contact the&nbsp;Admin on email info@ratedate.net</p>

app/views/static_pages/_terms_of_use.html.erb
<h1>Terms of Use</h1>
<h2>Our Rules</h2>
<p>We want you to enjoy using the site but we have to have a few rules to ensure it is a safe and enjoyable experience for everyone. This summary tells you the important bits and is intended as a guide only. Please note that you may only use the site if you agree to be bound by the full set of Terms of use (see section below this summary) and our Privacy Policy.</p>
<h2>Who are we?</h2>
<p>RateDate.net is the dating website. It will remain so until the introduction of the main functions. We provide the service on an "as is" basis and cannot guarantee that the service will be uninterrupted or error-free, or will achieve particular results.</p>
<h2>Who can use the site?</h2>
<p>You must be over 18 and you must not have been convicted of or currently be charged with any offence (or are subject to any court order, police investigation, formal caution or similar) specifically relating to fraud, assault, violence, sexual misconduct or harassment.</p>
<h2>Types of membership</h2>
<p>You may use the site for free as a guest or as a member. The most important feature that is only available to Subscribers is the ability to contact other members using the site's built in messaging systems.</p>
<h2>Safety</h2>
<p>Online dating should be a fun and safe experience. We do our best to ensure users are genuine but you must take responsibility at all times for your own safety. In particular, we would draw your attention to the following advice:<br />Never give out your own email address, mobile phone number or other contact details unless you have satisfied yourself that the person you are giving that information to is who they say they are and is to be trusted with such information.<br />Never give any money or any item of value to anyone who contacts you through the site.</p>
<p><strong>You may:</strong></p>
<ul>
  <li>Cancel your membership whenever you wish.</li>
</ul>
<p><strong>You must:</strong></p>
<ul>
  <li>Abide by our rules at all times.</li>
  <li>Notify us if you become aware of any other user of the site who is acting inappropriately or not in accordance with these rules.</li>
</ul>
<p><strong>You must not:</strong></p>
<ul>
  <li>Use the site in any way that might breach any applicable law, regulation or code of conduct.</li>
  <li>Include any false, misleading, offensive or sexually explicit content</li>
  <li>Include or attempt to include any contact details (including your surname) in your username, profile headline, profile or in any introductory messages</li>
  <li>Use, or attempt to use the site for any commercial purposes.</li>
  <li>Use any material that is subject to copyright restrictions</li>
  <li>Include or attempt to include any links to other websites.</li>
</ul>
<h2>User Content and information</h2>
<p>Rate Date is not the publisher of user content, therefore it is your sole responsibility to decide what information you include in your profile or any communication you may have with other users. Please remember that publicly visible information is just that!</p>
<p>We will never divulge any of your personal details to another user.</p>
<p>We may amend or remove all or part of your profile at our sole discretion.</p>
<p>We do not verify the accuracy of any information included in a user's profile, therefore you should always exercise caution and carry out your own validation before meeting someone in person, or passing on your contact details to them.</p>
<p>We always try to delete any offensive or inappropriate material as soon as we are aware of it. If you spot anything we have missed, please tell us.</p>
<h2>Rate Date Content</h2>
<p>All logos, graphics, images etc on the site are our or our partners intellectual property, and as such you may not use them for any purpose outside the intended scope of the site.</p>
<h2>You agree that you will not:</h2>
<ul>
  <li>in connection with the Services breach any applicable law, regulation or code of conduct;</li>
  <li>publish or send any User Content (including photos you make visible only to your favourites) or communications to us which are false or misleading (and you agree to update User Content to ensure that it does not become false or misleading), sexually explicit, sexually suggestive, vulgar, indecent, obscene, racist, homophobic, xenophobic, abusive, unlawful, deceitful, invasive of another's privacy, offensive, harmful, violent, threatening, harassing, defamatory, an infringement of third party intellectual property or other rights or which encourage or assist any of the foregoing. Photographic content that will be publicly viewable is further subject to the terms and conditions noted on the photo upload page;</li>
  <li>publish content (including photos) that directly or indirectly alludes to child pornography or attempts to solicit communication with or on behalf of any person under the age of 18;</li>
  <li>include in your profile or any other information you post on the Site or in any communications you make through the Site to another User who has not previously contacted you, any information that enables you to be personally identified or contacted (other than through the Services), including (but not limited to) your last name, postal or email address or telephone number or another website address where such information about you can be found. For the purposes of this restriction contact with another User through the "One liner" service does not qualify as prior contact;</li>
  <li>solicit other Users' contact details or disclose your subscription or Member status in your profile;</li>
  <li>disclose or make accessible to any third party any username(s), password(s), activation code(s) or similar information allocated to Users or use them for any purpose other than authentication for the Services;</li>
  <li>provide email addresses to us of other persons or publish or send any User Content referring to other persons without having obtained their prior consent;</li>
  <li>publish or send any User Content which links to any third party websites which are illegal or contain inappropriate content;</li>
  <li>use the Services for any commercial, professional or non-private purposes (including advertising, canvassing, soliciting, trading, prostitution);</li>
  <li>use the Services for junk mail, spam and pyramid or similar or fraudulent schemes;</li>
  <li>do anything which may have the effect of disrupting the Services including the use of worms, viruses, software bombs or mass mailings;</li>
  <li>attempt to gain unauthorized access to any part of the Services or to the equipment used to provide the Services;</li>
  <li>use the Services to harass any other Member or seek to contact any Member who requests that you cease contact (you will have the option to block contact from other Members by selecting the appropriate option in their profiles);</li>
  <li>impersonate any other person or entity; or</li>
  <li>use the Services other than for the purposes set out in these Terms.</li>
  <li>you agree to comply with any guidelines or requirements on our Site as well as any reasonable request or instructions by us in connection with the Services.</li>
  <li>you must ensure that all contact information (e.g. postal and email addresses) that you provide are accurate and kept up to date.</li>
</ul>

app/views/static_pages/home.html.erb
<div class="side-form">
    <div class="side-form-head">
      <span class="logo icon-logo"></span>
      <a id="hide-menu" class="close-menu" href="javascript:void(0)">
        <span class="fa fa-times"></span>
      </a>
    </div>

    <div class="login signup show">
      <p class="trigger">
        <a href="javascript:void(0)" class="left">Log In</a>
        <a href="javascript:void(0)" class="right">Sign Up</a>
      </p>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= devise_error_messages! %>
      <%= flash[:recaptcha_error] %>
      <div class="login-form active">
        <%= form_for(:user, as: resource_name, url: session_path(resource_name)) do |f| %>
            <p class="input">
              <%= f.email_field :email, autofocus: true, placeholder: "E-mail"   %>
            </p>

            <p class="input">
              <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
            </p>

            <% if devise_mapping.rememberable? %>
                <p class="checkbox">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </p>
            <% end %>

            <div class="center">
              <%= f.submit t('.sign_in'), class: 'round-btn' %>
            </div>
            <%= link_to 'Forgot Your Password?', new_password_path(resource_name), class: "link underline medium instructions" %>
            <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "link underline medium instructions" %>

        <% end %>
      </div>

      <div class="signup-form">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

            <%= f.hidden_field :referred_by, :value => session[:referred_by] %>
            <p class="input">
              <%= f.email_field :email, autofocus: true, placeholder: "Email" %>
            </p>

            <p class="input">
              <%= f.password_field :password, autocomplete: "off",  placeholder: "Password" %>
            </p>

            <p class="input">
              <%= f.password_field :password_confirmation, autocomplete: "off",  placeholder: "Repeat password" %>
            </p>
            <div class="captcha">
              <div class="captcha-wrap">
                <!-- INSERT CAPTCHA HERE -->
                <%= recaptcha_tags %>
              </div>
            </div>
            <div class="center">
              <%= f.submit t('sign_up'), class: 'round-btn' %>
            </div>
        <% end %>
        <%= link_to 'Forgot Your Password?', new_password_path(resource_name), class: "link underline medium instructions" %>
        <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "link underline medium instructions" %>

      </div>
    </div>

    <div class="check-mail">
      <span class="check-mail-icon"></span>
      <p class="check-mail-text">
        Thanks! Check your mail
        and follow instructions!
      </p>

      <div class="center">
        <button type="button" class="round-btn">Go to Log In</button>
      </div>
    </div>

    <div class="forgot">
      <p class="forgot-title">Forgot your password?</p>
      <p class="input">
        <input type="text" name="email" placeholder="E-mail" />
      </p>
      <div class="center">
        <button type="submit" class="round-btn">Send reset link</button>
      </div>
      <div class="center">
        <a class="link underline" href="javascript:void(0)">Log In</a>
        <a class="link underline" href="javascript:void(0)">Sign Up</a>
      </div>
    </div>


    <div class="info-links">
      <a class="link" href="javascript:void(0)" data-modal-target="#terms-of-use">Terms of Use</a>
      <a class="link" href="javascript:void(0)" data-modal-target="#privacy-policy">Policy</a>
    </div>

    <p class="info-text">
      RateDate © 2018
    </p>
</div>

<!-- SCREENS -->
<div class="landing-wrap">
  <div id="fullpage" >
    <div class="section">
      <div class="base-section">
        <span class="logo icon-logo"></span>

        <a id="show-menu" class="round-btn white" href="javascript:void(0)">Log In</a>

        <div class="revolution">
          <p>
            <span class="nowrap">REVOLUTION</span>
            <span class="nowrap">IN THE</span>
            <span class="nowrap">ONLINE DATING</span>
            <span class="nowrap">INDUSTRY</span>
          </p>
        </div>

        <div class="happiness">
          <p class="big-text">
            <span class="nowrap">Your happiness</span>
            <span class="nowrap">is closer</span>
            <span class="nowrap">than you think</span>
          </p>
          <div class="hidden-text-wrap">
            <p class="hidden-text">
              Rate Date – is a dating site, providing a unique opportunity to
              hold an online video date auction. This service makes it possible
              not only to find and communicate with interesting people, but create
              and take part in video date auctions as well.
            </p>
          </div>
        </div>

        <div class="video-circle">
          <video id="circle-video" loop poster=<%=image_url('video-poster.jpg')%>>
            <source src="/videos/first-video.m4v" type="video/mp4" />
            <source src="/videos/first-video.webm" type="video/webm" />
            <source src="/videos/first-video.ogv" type="video/ogg" />
          </video>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="second-section">
        <!-- NO CONTENT -->
      </div>
    </div>
    <div class="section">
      <div class="third-section">
        <span class="third-section-back"></span>
        <div class="section-title">
          <p class="section-title-index">01</p>
          <p class="section-title-label">Search</p>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="fourth-section">
        <span class="fourth-section-back"></span>
        <div class="section-title dark">
          <p class="section-title-index">02</p>
          <p class="section-title-label">Bid</p>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="fifth-section">
        <span class="fifth-section-back"></span>
        <div class="section-title">
          <p class="section-title-index">03</p>
          <p class="section-title-label">Watch</p>
        </div>
      </div>
    </div>

    <div class="section fp-auto-height">
      <div class="foot-section">
        <div class="links-row">
          <a href="javascript:void(0)" data-modal-target="#terms-of-use">Terms of Use</a>
          <a href="javascript:void(0)" data-modal-target="#privacy-policy">Policy</a>
        </div>
        <p class="copyright">Copyright © 2018 RateDate</p>
      </div>
    </div>
  </div>

  <ul class="nav-dots">
    <li data-menuanchor="section-1">
      <a href="#section-1"></a>
    </li>
    <li data-menuanchor="section-2">
      <a href="#section-2"></a>
    </li>
    <li data-menuanchor="section-3">
      <a href="#section-3"></a>
    </li>
    <li data-menuanchor="section-4">
      <a href="#section-4"></a>
    </li>
    <li data-menuanchor="section-5">
      <a href="#section-5"></a>
    </li>
  </ul>
</div>

app/views/static_pages/ico_landing.html.erb
<div class="container-fluid container-start">
  <nav class="navbar navbar-expand-lg navbar-dark bg-fade justify-content-between fixed-top">
    <a class="navbar-brand" href="#">
      <span class="icon-logo display-2"></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarICO" aria-controls="navbarICO" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarICO">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link" href="#"><%= t :about %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">white paper</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">bounty</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">token</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">road map</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">team</a>
        </li>
      </ul>
      <div class="navbar-nav">
        <div class="nav-item">
          <a class="btn btn-outline-danger mr-sm-2" href="#">login ICO</a>
        </div>
        <div class="nav-item">
          <a class="btn btn-outline-danger my-2 my-sm-0" href="#">join ICO</a>
        </div>
      </div>
    </div>
  </nav>
  <div class="row justify-content-md-center">
    <div class="col-md-8 text-center">
      <img class="img-fluid" src="http://dummyimage.com/960x540" />
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-4 text-center text-light pt-3">
      <h2>Pre-ICO Start</h2>
      <div class="row">
        <div class="col-md-3">
          <small>Days</small>
          <div class="display-3" id="tDayNum">--</div>
        </div>
        <div class="col-md-3">
          <small>Hours</small>
          <div class="display-3" id="tHourNum">--</div>
        </div>
        <div class="col-md-3">
          <small>Minutes</small>
          <div class="display-3" id="tMinNum">--</div>
        </div>
        <div class="col-md-3">
          <small>Seconds</small>
          <div class="display-3" id="tSecNum">--</div>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-4 text-center text-light pt-3">
      <div class="row">
        <div class="col-md-6">
          <span class="display-4 icon-bitcoin"></span>
          <span class="display-3">0</span>
        </div>
        <div class="col-md-6">
          <span class="display-4 icon-ethereum"></span>
          <span class="display-3">0</span>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-4 text-center text-light pt-3"></div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center p-3">~~~~</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8"><img class="img-fluid" src="http://dummyimage.com/1200x600" /></div>
    <div class="col-md-4">
      <h2 class="text-center p-3">Rate Date Idea</h2>
      <p>Rate Date - это сайт знакомств с уникальной возможностью проведения онлайн аукциона видео-свиданий.</p>

      <p>С помощью данного сервиса можно не только находить и общаться с интересными людбьми, но и создавать и участвовать в аукционах видео-свиданий. Rate Date включает в себя широкий спектр функций, главными из которых являются: простой доступ к сервису, бесграничное общение, возможность участвовать в онлайн аукционах видео-свиданий в качестве участника торгов (Rater) и соискателя (Dater).</p>

      <p>Dater - зарегистрированый пользователь сайта Rate Date, который выставляет свой профайл на онлайн аукцион видео-свиданий.</p>
      <p>Rater - зарегистрированый пользователь сайта Rate Date, который участвует в торгах онлайн аукциона видео-свиданий.</p>

      <p>Главной целью компании Rate Date является объединение как можно большего коичества одиноких сердец и упрощение знакомства людей в эпоху высоких технологий.</p>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center p-3">~~~~</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h2 class="text-center p-3">Business Model</h2>
      <p>Сервис Rate Date является бесплатным и свободным сайтом знакоств. Главными способами монетизации проекта являются: возможность приобретения премиум-аккаунтов в которые входит расширеный функционал; и взымание комиссии с проводимых онлайн аукционов видео-свиданий.</p>
      <ul>
        <li>Премиум аккаунт приобретается на различные отрезки времени с учтенной системой скидок.</li>
        <li>Комиссия предполагает снятие фиксированого процента от выигрышной ставки Rater. Остаток суммы перечисляется на счет Dater.</li>
      </ul>
      <p>100% средств полученных от работы сайта пойдут на развитие Rate Date</p>
      <p>Присоединяйтесь к Rate Date и получайте высокую прибыль за счет роста цены токена</p>
    </div>
    <div class="col-md-8"><img class="img-fluid" src="http://dummyimage.com/1200x600" /></div>
  </div>
</div>

app/views/static_pages/in_develop.html.erb
<div class="container-fluid container-start">
  <div class="row justify-content-md-center">
    <div class="col-lg-4 text-center">
      <div class="nav justify-content-center">
        <a href="http://ratedate.net" class="nav-link"><span class="icon-logo text-light big-logo"></span></a>
      </div>
      <div class="h2 text-light p-3">RateDate is under development. Take a cup of tea or coffee and<br> follow us:</div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-3 justify-content-center pt-3 nav">
      <a href="https://www.facebook.com/Rate-Date-861947790626663/" class="icon-facebook h1 nav-link text-light"></a>
      <a href="https://twitter.com/RateDate2" class="icon-twitter h1 nav-link text-light"></a>
      <a href="https://t.me/joinchat/FnaGEQvA8Z54oH4AM2vIIQ" class="icon-telegram h1 nav-link text-light"></a>
      <a href="https://medium.com/@usatenko.katerina" class="icon-medium h1 nav-link text-light"></a>
    </div>
  </div>
</div>

app/views/static_pages/privacy_policy.html.erb
<h1>Privacy Policy</h1>
<p>RateDate.net has created this privacy statement in order to demonstrate our commitment to privacy. The following discloses the information-gathering and dissemination practices for this web site.</p>
<h2>Information is Automatically Logged</h2>
<p>This site uses a visitor statistics package that logs the following information on each page access: userid, IP, host, browser type, computing platform, date and time, page viewed, referer, request type, and query_string. We use this information to help diagnose problems with our server and to administer our web site, and to help identify you. This information is also gathered because we like to see who is visiting.&nbsp;This information is not and will never be divulged to a third party unless required by law.</p>
<h2>Cookies</h2>
<p>This site uses cookies to deliver content specific to your interests, to save your password so you don't have to re-enter it each time you visit our site, and for other purposes.</p>
<h2>Registration Forms</h2>
<p>Our site's registration form requires users to give us contact information (i.e. email address). Contact information from the registration forms is used to validate the user's account. This enables the site administrators to provide moderation for the various public features of this site, and to get in touch with the user when necessary.&nbsp;This information is not and will never be divulged to a third party unless required by law.&nbsp;We use this data to tailor our visitor's experience at our site showing them content that we think they might be interested in, and displaying the content according to their preferences.</p>
<h2>External Links</h2>
<p>This site contains links to other sites. RateDate.net is not responsible for the privacy practices or the content of such web sites.</p>
<h2>Personal data</h2>
<p>Please remember that any information that is disclosed in this areas becomes public information and you should exercise caution when deciding to disclose your personal information. All postings are property of their respective author. Improper language is automatically censored by the system. All submissions are subject to our editorial control -- editorial changes will be indicated.</p>
<h2>Security</h2>
<p>This site has security measures in place to protect the loss, misuse, and alteration of the information under our control.</p>
<h2>Data Quality/Access</h2>
<p>This site gives users control over their user experience and content that they may have provided. Users can in some cases freely modify or delete any content they post for a limited time.</p>
<h2>Limitation of Liability</h2>
<p>RateDate.net is not liable for any damages caused by any of the site content, whether directly provided by RateDate.net its employees or not.</p>
<h2>Contacting the Web Site</h2>
<p>If you have any questions about this privacy statement, the practices of this site, or your dealings with this web site, you can contact the&nbsp;Admin on email info@ratedate.net</p>