config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'



  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => { omniauth_callbacks: 'omniauth_callbacks'}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  constraints subdomain: 'ico' do
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
      scope module: 'ico', as: 'ico' do
        devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "ico/registrations" }
        devise_scope :ico_user do
          get 'sign_in', to: 'sessions#new', module: 'ico'
          delete 'sign_out', to: 'sessions#destroy', module: 'ico'
          get 'sign_up', to: 'registrations#new', module: 'ico'
        end
        root 'static_pages#ico_landing', module: 'ico'
        get 'static_pages/ico_landing'
        get 'static_pages/in_develop'
        get 'account', to: 'account#index'
        post 'account/add_eth'
        post 'kyc/create'
        resources :etz_investments
      end
      root 'static_pages#ico_landing', module: 'ico'
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
    root 'static_pages#ico_landing', module: 'ico'
  end
  root 'static_pages#home'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
    resources :profiles, except: [:edit, :destroy]
    resources :auctions, except: [:destroy]
    get 'my_profile', to: 'profiles#show', as: 'my_profile'
    get 'my_profile/edit', to: 'profiles#edit', as: 'edit_my_profile'
    get 'my_bids', to: 'auctions#my_bids', as: 'auctions_my_bids'
    get 'auctions/:id/videodate', to: 'auctions#videodate', as: 'auctions_videodate'
    resources :personal_messages, only: [:new,  :create]
    resources :conversations, only: [:index, :show]
    root 'static_pages#in_develop'
    get 'terms_of_use', to: 'static_pages#terms_of_use'
    get 'privacy_policy', to: 'static_pages#privacy_policy'
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" }
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
      get 'sign_up', to: 'devise/registrations#new'
    end
    resources :promos, except: [:edit, :destroy]
    post 'activate_promo', to: 'promos#activate'
    post 'payment', to: 'payments#payment'
    post 'payment_result', to: 'payments#payment_result'
    get 'payment', to: 'payments#payment_redirect'
    get 'payment_result', to: 'payments#payment_redirect'
  end
  post 'process_payment_result', to: 'payments#process_payment_result'
  get 'process_payment_result', to: 'payments#payment_redirect'
  resources :conversations, only: [:index]
end

app/models/profile.rb
class Profile < ApplicationRecord
  include Filterable

  belongs_to :user
  belongs_to :city
  has_many :photos
  has_many :auctions
  has_many :bids, -> {includes :auction}
  has_many :bid_auctions, -> { distinct }, through: :bids, source: :auction
  has_many :winning_auctions, class_name: 'Auction', foreign_key: 'winner_id'
  # Used for user avatar image edit
  attr_accessor :city_name, :administrative_area_level_1, :administrative_area_level_2, :country, :country_code
  accepts_nested_attributes_for :photos, allow_destroy: true

  before_validation :set_city

  validates_presence_of :avatar
  validates :name, :surname, :gender, :timezone, :dob, :presence => true


  mount_uploader :avatar, AvatarUploader
  # acts_as_taggable
  acts_as_ordered_taggable_on :hobbies, :musics, :films, :books

  scope :by_country, -> (country) {where city_id: City.where(country: country) }
  scope :by_city, -> (city) {where city_id: city }
  scope :by_gender, -> (gender) {where gender: gender}
  scope :by_age_from, -> (age_from) {where 'dob <= ?', Date.today - age_from.to_i.year}
  scope :by_age_to, -> (age_to) {where 'dob >= ?', Date.today - age_to.to_i.year}
  def set_city
    if self.city_name
      city = City.find_or_create_by(city: self.city_name, country: self.country, country_code: self.country_code, administrative_area_level_1: self.administrative_area_level_1, administrative_area_level_2: self.administrative_area_level_2)
      self.city_id = city.id
    end
  end
  def age
    now = Time.now.utc.to_date
    now.year - self.dob.year - ((now.month > self.dob.month || (now.month == self.dob.month && now.day >= self.dob.day)) ? 0 : 1)
  end
  def display_name
    display_name = name
    display_name += ' "'+nickname+'" ' if !nickname.blank?
    display_name += ' '+surname if !hide_surname
    display_name
  end
  def small_avatar
    url = ActionController::Base.helpers.asset_url 'avatar_placeholder.png'
    if avatar.present?
      if avatar.small_avatar.file.present?
        url = avatar.url(:small_avatar)
      end
    end
    url
  end
  def medium_avatar
    url = ActionController::Base.helpers.asset_url 'avatar_placeholder.png'
    if avatar.present?
      if avatar.medium_avatar.file.present?
        url = avatar.url(:medium_avatar)
      end
    end
    url
  end
  def large_avatar
    url = ActionController::Base.helpers.asset_url 'avatar_placeholder.png'
    if avatar.present?
      if avatar.large_avatar.file.present?
        url = avatar.url(:large_avatar)
      end
    end
    url
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.filter(params.slice(:by_country, :by_city, :by_gender, :by_age_from, :by_age_to)).where.not(id: current_user.profile)
    if params[:by_gender].nil?
      @profiles = @profiles.order 'gender '+(current_user.profile.gender=='male' ? 'ASC' : 'DESC')
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    redirect_to new_profile_path if !@profile
  end

  # GET /profiles/new
  def new
    if current_user.profile.present?
      redirect_to current_user.profile
    end
    @profile = Profile.new
    6.times {@profile.photos.build}
  end

  # GET /profiles/1/edit
  def edit
    if @profile.photos.any?
      (6-@profile.photos.count).times {@profile.photos.build}
    else
      6.times {@profile.photos.build}
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        if params['profile']['crop_x']&&@profile.avatar.present?
          @profile.avatar.recreate_versions!
        end
        format.html { redirect_to my_profile_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        if params['profile']['crop_x']
          @profile.avatar.recreate_versions!
        end
        format.html { redirect_to my_profile_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = params[:id] ? Profile.find(params[:id]) : current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :surname, :hide_surname, :nickname, :timezone, :avatar, {:languages => []}, :dob, :hide_dob, :gender, :about, :crop_x, :crop_y, :crop_w, :crop_h, :hobby_list, :music_list, :film_list, :book_list, :country, :country_code, :city_name, :administrative_area_level_1, :administrative_area_level_2, photos_attributes:[:id,:photo,:remove_photo])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.bkp.html.erb
<%= form_with(model: profile, local: true) do |form| %>
    <% if profile.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

          <ul>
            <% profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <% img_src = @profile.avatar.present? ? @profile.avatar.url : image_url('avatar_placeholder.png') %>
      <div class="row">
        <div class="col-xl-6">
          <img id="img_preview" src="<%= img_src %>" alt="Avatar" class="img-fluid"/>
        </div>
      </div>
      <%= form.file_field :avatar, id: :profile_avatar %>
      <%= form.hidden_field :avatar_cache %>
    </div>
    <%= form.hidden_field :crop_x, id: :crop_x %>
    <%= form.hidden_field :crop_y, id: :crop_y %>
    <%= form.hidden_field :crop_w, id: :crop_w %>
    <%= form.hidden_field :crop_h, id: :crop_h %>

    <div class="form-group form-row">
      <%= form.fields_for :photos do |p| %>
          <div class="col-lg-2">
            <label>
              <img src="<%= p.object.new_record? ? asset_path('avatar_placeholder.png') : p.object.photo.url(:thumb) %>" class="img-fluid">
              <%= p.file_field :photo, class: 'd-none' %>
            </label>
          </div>
      <% end %>
    </div>

    <div class="form-group form-row">
      <div class="col-lg-6">
        <%= form.text_field :name, id: :profile_name, class: 'form-control', placeholder: 'Name' %>
      </div>
      <div class="col-lg-6">
        <%= form.text_field :surname, id: :profile_surname, class: 'form-control', placeholder: 'Surname' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :hide_surname %>
      <%= form.check_box :hide_surname, id: :profile_hide_surname %>
    </div>

    <div class="form-group">
      <%= form.text_field :nickname, id: :profile_nickname, class: 'form-control', placeholder: 'Nickname' %>
    </div>

    <div class="form-group">
      <%= form.select :languages, options_for_select(languages, @profile.languages), {include_hidden: false }, {multiple: true, id: 'profile_languages', class: 'form-control'} %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, id: :profile_address, class: 'form-control' %>
    </div>
    <div class="form-group row">
      <div class="col-lg">
        <%= form.text_field :country, id: :profile_country, class: 'form-control', readonly: true, placeholder: 'Country', value: (@profile.city.country if @profile.city.present?) %>
        <%= form.hidden_field :country_code, id: :profile_country_code, value: (@profile.city.country_code if @profile.city.present?) %>
      </div>
      <div class="col-lg">
        <%= form.text_field :state, id: :profile_state, class: 'form-control', disabled: true, placeholder: 'State', value: (@profile.city.administrative_area_level_1+@profile.city.administrative_area_level_2 if @profile.city.present?) %>
        <%= form.hidden_field :administrative_area_level_1, id: :administrative_area_level_1, value: (@profile.city.administrative_area_level_1 if @profile.city.present?) %>
        <%= form.hidden_field :administrative_area_level_2, id: :administrative_area_level_2, value: (@profile.city.administrative_area_level_2 if @profile.city.present?) %>
      </div>
      <div class="col-lg">
        <%= form.text_field :city_name, id: :profile_city, class: 'form-control', readonly: true, placeholder: 'City', value: (@profile.city.city if @profile.city.present?) %>
      </div>
    </div>


    <div class="form-group">
      <%= form.label :dob %>
      <%= form.date_select :dob, id: :profile_dob, start_year: Date.today.year-18, end_year: 1920 %>
    </div>

    <div class="form-group">
      <%= form.label :hide_dob %>
      <%= form.check_box :hide_dob, id: :profile_hide_dob %>
    </div>

    <div class="form-group">
      <%= form.label :gender %>
      <%= form.radio_button :gender, "male", id: :profile_gender %>
      <%= form.label :gender, "Male" %>
      <%= form.radio_button :gender, "female", id: :profile_gender %>
      <%= form.label :gender, "Female" %>
    </div>

    <div class="form-group">
      <%= form.label :about %>
      <%= form.text_area :about, id: :profile_about, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :hobby_list, 'Hobbies' %>
      <%= form.text_field :hobby_list, id: :hobby_list, value: @profile.hobby_list.join(', '), 'data-role' => 'tagsinput'  %>
    </div>
    <div class="form-group">
      <%= form.label :film_list, 'Movies' %>
      <%= form.text_field :film_list, id: :film_list, value: @profile.film_list.join(', '), 'data-role' => 'tagsinput' %>
    </div>
    <div class="form-group">
      <%= form.label :music_list, 'Music' %>
      <%= form.text_field :music_list, id: :music_list, value: @profile.music_list.join(', '), 'data-role' => 'tagsinput' %>
    </div>
    <div class="form-group">
      <%= form.label :book_list, 'Books' %>
      <%= form.text_field :book_list, id: :book_list, value: @profile.book_list.join(', '), 'data-role' => 'tagsinput' %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/profiles/_gifts.html.erb
<div class="modal" id="gifts">
  <a class="modal-close" href="javascript:void(0)">
    <i class="fa fa-times"></i>
  </a>

  <div class="modal-window">
    <div class="modal-content center">
      <h1>Coming Soon</h1>
    </div>
  </div>
</div>

app/views/profiles/_profile.html.erb
<div class="cell">
  <div class="profile">
    <span class="profile-image">
      <%= link_to profile do %>
        <%= image_tag profile.medium_avatar %>
      <% end %>
    </span>
    <div class="profile-info">
      <p class="name">
        <%= link_to profile do %>
          <span class="truncate-xs"><%= profile.display_name %></span><span>, <%= profile.age %></span>
        <% end %>
      </p>
      <p class="place">
        <%= profile.city.country+', '+profile.city.city if profile.city.present? %>
      </p>

      <div class="profile-info-buttons">
        <a class="red" href="javascript:void(0)" data-modal-target="#gifts"><i class="fa fa-gift"></i></a>
        <%= link_to '<i class="fa fa-comment"></i>'.html_safe, new_personal_message_path(receiver_id: profile.user), class: 'yellow'%>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<% content_for :head do %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZtLop0Yk-dl1d9Ord1Hc7nsrak_Mat44&libraries=places&language=en" data-turbolinks-track="reload"></script>

<% end %>
<div class="profile-page with-button">
  <div class="profile-page-wrap">

    <div class="top">
      <%= link_to '<i class="fa fa-chevron-left"></i>Back'.html_safe, url_for(:back), class: 'back-link' %>
    </div>
    <%= render 'form', profile: @profile %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    var options = {types: ['(cities)']};
    var input = document.getElementById('profile_address');
    window.autocomplete = new google.maps.places.Autocomplete(input, options);
    fillInAddress = function() {
        var addressType, i, place, state;
        place = autocomplete.getPlace();
        i = 0;
        state = '';
        document.getElementById('administrative_area_level_1').value = '';
        document.getElementById('administrative_area_level_2').value = '';
        while (i < place.address_components.length) {
            addressType = place.address_components[i].types[0];
            if (addressType === "locality") {
                document.getElementById('profile_city').value = place.address_components[i]['long_name'];
            }
            if (addressType === "administrative_area_level_1" || addressType === "administrative_area_level_2") {
                if (state !== '') {
                    state += ', ';
                }
                state += place.address_components[i]['long_name'];
                document.getElementById(addressType).value = place.address_components[i]['long_name'];
            }
            if (addressType === "country") {
                document.getElementById('profile_country').value = place.address_components[i]['long_name'];
                document.getElementById('profile_country_code').value = place.address_components[i]['short_name'];
            }
            i++;
        }
        return document.getElementById('profile_state').value = state;
    };
    window.autocomplete.addListener('place_changed', fillInAddress);
</script>

app/views/profiles/index.html.erb
<% notice %>
<div class="profiles">
  <div class="profiles-wrap">
    <div class="filter-form" id="filters-form">
      <%= render 'search_form' %>
    </div>
    <div class="filter-bar">
      <a class="toggle-filter" id="show-filters" href="javascript:void(0)">
        <i class="fa fa-filter"></i> Filter Profiles
      </a>

    </div>

    <div class="grid-xs-1 grid-xsc-2 grid-sm-2 grid-md-3 grid-lg-4">
      <%= render @profiles %>
    </div>
  </div>
</div>
<%= render 'gifts' %>

app/views/profiles/new.html.erb
<% content_for :head do %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZtLop0Yk-dl1d9Ord1Hc7nsrak_Mat44&libraries=places&language=en" data-turbolinks-track="reload"></script>

<% end %>
<div class="profile-page with-button">
  <div class="profile-page-wrap">

    <div class="top">
      <%= link_to '<i class="fa fa-chevron-left"></i>Back'.html_safe, url_for(:back), class: 'back-link' %>
    </div>
    <%= render 'form', profile: @profile %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    var options = {types: ['(cities)']};
    var input = document.getElementById('profile_address');
    window.autocomplete = new google.maps.places.Autocomplete(input, options);
    fillInAddress = function() {
        var addressType, i, place, state;
        place = autocomplete.getPlace();
        i = 0;
        state = '';
        document.getElementById('administrative_area_level_1').value = '';
        document.getElementById('administrative_area_level_2').value = '';
        while (i < place.address_components.length) {
            addressType = place.address_components[i].types[0];
            if (addressType === "locality") {
                document.getElementById('profile_city').value = place.address_components[i]['long_name'];
            }
            if (addressType === "administrative_area_level_1" || addressType === "administrative_area_level_2") {
                if (state !== '') {
                    state += ', ';
                }
                state += place.address_components[i]['long_name'];
                document.getElementById(addressType).value = place.address_components[i]['long_name'];
            }
            if (addressType === "country") {
                document.getElementById('profile_country').value = place.address_components[i]['long_name'];
                document.getElementById('profile_country_code').value = place.address_components[i]['short_name'];
            }
            i++;
        }
        return document.getElementById('profile_state').value = state;
    };
    window.autocomplete.addListener('place_changed', fillInAddress);
</script>

app/views/profiles/new_photos.html.erb
<%= form_for @profile do |f| %>
    <%= f.fields_for :photos do |p| %>
        <div class="col-lg-3">
          <label>
            <img src="<%= asset_path('avatar_placeholder.phg') %>" class="img-fluid">
            <% p.file_field :photo %>
          </label>
        </div>
    <% end %>
<% end %>

app/views/profiles/show.html.erb
<div class="profile-page">
  <div class="profile-page-wrap">
    <div class="main">
      <div class="profile-big">
        <div class="profile-big-image">
          <%= image_tag @profile.large_avatar %>
        </div>
        <div class="profile-big-info">
          <p class="name"><%= @profile.display_name %> <%= @profile.surname if @profile.hide_surname&&@profile==current_user.profile%>, <%= @profile.age %></p>
          <p class="place"><%= @profile.city.country if @profile.city %>, <%= @profile.city.city if @profile.city %></p>
          <% if @profile==current_user.profile %>
              <%= link_to 'Edit profile', edit_my_profile_path, class: 'round-btn transparent edit' %>
          <% else %>
            <div class="buttons">
              <%= link_to  new_personal_message_path(receiver_id: @profile.user), class: 'round-btn transparent send-message' do %>
                <i class="fa fa-comment"></i>
                <span class="btn-text">Message</span>
              <% end %>
              <button class="round-btn transparent send-gift" type="button" data-modal-target="#gifts">
                <i class="fa fa-gift"></i>
                <span class="btn-text">Send a gift</span>
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="side">
      <div class="profile-gallery">
        <p class="profile-gallery-title">
          <span>Photos</span>
        </p>

        <ul class="slider-lg" id="profile-gallery">
          <% @profile.photos.each do |photo| %>
              <li>
                <span class="profile-gallery-image">
                    <%= image_tag photo.photo.url(:thumb) %>
                </span>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="clear"></div>
    <div class="side">
      <% if @profile.auctions.active.any? %>
      <% auction = @profile.auctions.active.last %>
      <div class="profile-auction" id="auction_<%= auction.id %>">
        <% if auction.is_charitable? %>
            <span class="icon-rd-heart charitable"></span>
        <% end %>
        <p class="profile-auction-title">Auction</p>
        <p class="profile-auction-aim">The aim of auction - <%= auction.aim %></p>
        <div class="profile-auction-bid-info">
          <div class="bid-value">
            <div class="title"><%= auction.bids.any? ? 'Highest Bid' : 'Starts at' %></div>
            <div class="value"><span><%= auction.bids.any? ? "%g"%auction.bids.last.bid_value : "%g"%auction.start_bid %></span> RDT</div>
          </div>
          <div class="bid-count">
            <div class="title">Bids</div>
            <div class="value"><span><%= auction.bids.count %></span></div>
          </div>
        </div>
        <div class="profile-auction-timer">
          <div class="profile-auction-timer-title">End </div>
          <div class="profile-auction-timer-value"><%= auction.auction_end.in_time_zone(show_timezone).strftime('%B %d %H:%M') %></div>
          <% progress = (DateTime.now.to_time-auction.created_at.to_time)/(auction.auction_end.to_time-auction.created_at.to_time)*100 %>
          <div class="profile-auction-timer-progress"><div class="profile-auction-timer-progress-bar" style="width: <%= progress %>%"></div></div>
        </div>
        <% if @profile.user == current_user %>
        <div class="buttons">
          <%= link_to 'Edit', edit_auction_path(auction), class: 'button-red' %>
        </div>
        <% else %>
          <div class="bid-form">
            <form action="">
              <input id="auction_bid_<%= auction.id %>" type="number" value="<%= auction.bids.any? ? "%g"%(auction.bids.last.bid_value+auction.bid_step) : "%g"%auction.start_bid %>">
              <a href="javascript:void(0)" class="button-bid" data-auction="<%= auction.id %>">Bid</a>
            </form>
          </div>
        <% end %>
      </div>
      <% end %>
      <div class="profile-about">
        <p class="profile-about-title"> About </p>
        <p class="profile-about-message"><%= @profile.about %></p>

        <div class="profile-about-item">
          <p class="title">Languages</p>
          <p class="value">
            <%= languages_list(@profile.languages) if  @profile.languages %>
          </p>
        </div>

        <div class="profile-about-item">
          <p class="title">Music</p>
          <p class="value"><%= @profile.music_list %></p>
        </div>

        <div class="profile-about-item">
          <p class="title">Movies</p>
          <p class="value"><%= @profile.film_list %></p>
        </div>

        <div class="profile-about-item">
          <p class="title">Books</p>
          <p class="value"><%= @profile.book_list %></p>
        </div>

        <div class="profile-about-item">
          <p class="title">Hobbies</p>
          <p class="value"><%= @profile.hobby_list %></p>
        </div>

        <a class="read-more" href="javascript:void(0)">Read more</a>
      </div>
    </div>
    <div class="main">
      <ul class="slider-lg with-offset">
        <li>
          <a class="profile-no-gift" href="javascript:void(0)" data-modal-target="#gifts">
            <p class="profile-no-gift-icon">
              <i class="fa fa-gift"></i>
            </p>
            <p class="profile-no-gift-caption">
              Be the first! Send a gift!
            </p>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>
<%= render 'gifts' %>

app/views/profiles/tmp.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @profile.large_avatar, class: 'img-thumbnail' %>
  </div>
  <div class="col-md-8">
    <h2>
      <%= @profile.display_name %> <%= @profile.surname if @profile.hide_surname&&@profile==current_user.profile%>
    </h2>
    <%= link_to('Edit Profile', edit_my_profile_path, class: 'btn btn-secondary') if @profile==current_user.profile %>
    <%= link_to(' Send a Message', new_personal_message_path(receiver_id: @profile.user), class: 'btn btn-secondary icon-envelope') if @profile!=current_user.profile%>
    <div>
      <%= @profile.age %> <%= t '.years_old' %>
    </div>
    <p>
      <%= @profile.city.country if @profile.city %>
      <%= @profile.city.city if @profile.city %>
    </p>

    <p>
      <strong>Languages</strong>
      <% if  @profile.languages
           @profile.languages.each do |l| %>
              <%= language(l) %>,
          <% end %>
      <% end %>
    </p>

    <p>
      <strong>About:</strong>
      <br>
      <%= @profile.about %>
    </p>

    <p>
      <strong>Hobbies:</strong>
      <br>
      <%= @profile.hobby_list %>
    </p>
    <p>
      <strong>Music:</strong>
      <br>
      <%= @profile.music_list %>
    </p>
    <p>
      <strong>Movies:</strong>
      <br>
      <%= @profile.film_list %>
    </p>
    <p>
      <strong>Books:</strong>
      <br>
      <%= @profile.book_list %>
    </p>

  </div>
</div>
<div class="row pt-2">
  <% @profile.photos.each_with_index do |photo,index| %>
      <div class="col-lg-2 col-sm-4">
        <%= link_to(photo.photo.url, :'data-toggle'=>'lightbox', :'data-gallery'=>'profile-gallery' ) do %>
            <%= image_tag photo.photo.url(:thumb), class: 'img-thumbnail w-100' %>
        <% end %>
      </div>
  <% end %>
</div>