config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'



  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => { omniauth_callbacks: 'omniauth_callbacks'}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  constraints subdomain: 'ico' do
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
      scope module: 'ico', as: 'ico' do
        devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "ico/registrations" }
        devise_scope :ico_user do
          get 'sign_in', to: 'sessions#new', module: 'ico'
          delete 'sign_out', to: 'sessions#destroy', module: 'ico'
          get 'sign_up', to: 'registrations#new', module: 'ico'
        end
        root 'static_pages#ico_landing', module: 'ico'
        get 'static_pages/ico_landing'
        get 'static_pages/in_develop'
        get 'account', to: 'account#index'
        post 'account/add_eth'
        post 'kyc/create'
        resources :etz_investments
      end
      root 'static_pages#ico_landing', module: 'ico'
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
    root 'static_pages#ico_landing', module: 'ico'
  end
  root 'static_pages#home'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
    resources :profiles, except: [:edit, :destroy]
    resources :auctions, except: [:destroy]
    get 'my_profile', to: 'profiles#show', as: 'my_profile'
    get 'my_profile/edit', to: 'profiles#edit', as: 'edit_my_profile'
    get 'my_bids', to: 'auctions#my_bids', as: 'auctions_my_bids'
    get 'auctions/:id/videodate', to: 'auctions#videodate', as: 'auctions_videodate'
    resources :personal_messages, only: [:new,  :create]
    resources :conversations, only: [:index, :show]
    root 'static_pages#in_develop'
    get 'terms_of_use', to: 'static_pages#terms_of_use'
    get 'privacy_policy', to: 'static_pages#privacy_policy'
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" }
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
      get 'sign_up', to: 'devise/registrations#new'
    end
    resources :promos, except: [:edit, :destroy]
    post 'activate_promo', to: 'promos#activate'
    post 'payment', to: 'payments#payment'
    post 'payment_result', to: 'payments#payment_result'
    get 'payment', to: 'payments#payment_redirect'
    get 'payment_result', to: 'payments#payment_redirect'
  end
  post 'process_payment_result', to: 'payments#process_payment_result'
  get 'process_payment_result', to: 'payments#payment_redirect'
  resources :conversations, only: [:index]
end

app/models/promo.rb
class Promo < ApplicationRecord
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promo, only: [:show, :edit, :update, :destroy]
  before_action :is_super_admin, except: [:activate]

  # GET /promos
  # GET /promos.json
  def index
    if params[:promo_create_session]
      @promos = Promo.where('create_session=?', params[:promo_create_session])
    else
      @promos = Promo.all
    end
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  def bunch_create
    @create_session = SecureRandom.urlsafe_base64
    session[:promo_create_session] = @create_session
    @number = promo_params[:number]
    @value = promo_params[:value]
    @string = promo_params[:string].parameterize
    @user_id = current_user.id
    @count = 0
    while @count < @number
      promo = Promo.new(user_id: @user_id, value: @value, create_session: @create_session)
      promo.promocode = @string+'-'+SecureRandom.hex(2)
      if promo.save!
        @count += 1
      end
    end
  end

  def activate
    if params[:promocode]
      @promo = Promo.where('promocode=?',params[:promocode]).last
      if @promo
        if @promo.status == 'available' && @promo.promo_type == 'rdt'
          if current_user.balance.present?
            current_user.balance.add_amount(@promo.value)
          else
            current_user.create_balance()
            current_user.balance.add_amount(@promo.value)
          end
          @promo.update(status: 'used')
          redirect_to my_profile_path, notice: 'Promo code successfully used'
        else
          redirect_to my_profile_path, notice: 'Promo code are wrong or already used'
        end
      end
    end
  end

  # POST /promos
  # POST /promos.json
  def create
    @create_session = SecureRandom.urlsafe_base64
    @number = promo_params[:number]
    @value = promo_params[:value]
    @string = promo_params[:string].parameterize
    @user_id = current_user.id
    @count = 0
    while @count < @number.to_i
      promo = Promo.new(user_id: @user_id, value: @value, create_session: @create_session)
      promo.promocode = @string+'-'+SecureRandom.hex(2)
      if promo.save
        @count += 1
      end
    end
    redirect_to promos_url(promo_create_session: @create_session), notice: 'Promos was successfully created.'
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:value, :string, :number)
    end

    def is_super_admin
      redirect_to my_profile_path if !current_user.superadmin?
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_with(model: promo, local: true) do |form| %>
  <% if promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% promo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :promo_string %>
  </div>
  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :promo_number %>
  </div>
  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :promo_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing Promo</h1>

<%= render 'form', promo: @promo %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="profiles">
  <div class="profiles-wrap">
    <p id="notice"><%= notice %></p>

    <h1>Promos</h1>

    <table>
      <thead>
      <tr>
        <th>Promo Code</th>
        <th>Value</th>
      </tr>
      </thead>

      <tbody>
      <% @promos.each do |promo| %>
          <tr>
            <td><%= promo.promocode %></td>
            <td><%= promo.value %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Promos', new_promo_path, class: 'round-btn' %>
  </div>
</div>

app/views/promos/new.html.erb
<p id="notice"><%= notice %></p>
<div class="profiles">
  <div class="profiles-wrap">
    <h1>New Promos</h1>

    <%= render 'form', promo: @promo %>

    <%= link_to 'Back', promos_path %>
  </div>
</div>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>