config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'



  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => { omniauth_callbacks: 'omniauth_callbacks'}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  constraints subdomain: 'ico' do
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
      scope module: 'ico', as: 'ico' do
        devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "ico/registrations" }
        devise_scope :ico_user do
          get 'sign_in', to: 'sessions#new', module: 'ico'
          delete 'sign_out', to: 'sessions#destroy', module: 'ico'
          get 'sign_up', to: 'registrations#new', module: 'ico'
        end
        root 'static_pages#ico_landing', module: 'ico'
        get 'static_pages/ico_landing'
        get 'static_pages/in_develop'
        get 'account', to: 'account#index'
        post 'account/add_eth'
        post 'kyc/create'
        resources :etz_investments
      end
      root 'static_pages#ico_landing', module: 'ico'
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
    root 'static_pages#ico_landing', module: 'ico'
  end
  root 'static_pages#home'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}  do
    resources :profiles, except: [:edit, :destroy]
    resources :auctions, except: [:destroy]
    get 'my_profile', to: 'profiles#show', as: 'my_profile'
    get 'my_profile/edit', to: 'profiles#edit', as: 'edit_my_profile'
    get 'my_bids', to: 'auctions#my_bids', as: 'auctions_my_bids'
    get 'auctions/:id/videodate', to: 'auctions#videodate', as: 'auctions_videodate'
    resources :personal_messages, only: [:new,  :create]
    resources :conversations, only: [:index, :show]
    root 'static_pages#in_develop'
    get 'terms_of_use', to: 'static_pages#terms_of_use'
    get 'privacy_policy', to: 'static_pages#privacy_policy'
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" }
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      delete 'sign_out', to: 'devise/sessions#destroy'
      get 'sign_up', to: 'devise/registrations#new'
    end
    resources :promos, except: [:edit, :destroy]
    post 'activate_promo', to: 'promos#activate'
    post 'payment', to: 'payments#payment'
    post 'payment_result', to: 'payments#payment_result'
    get 'payment', to: 'payments#payment_redirect'
    get 'payment_result', to: 'payments#payment_redirect'
  end
  post 'process_payment_result', to: 'payments#process_payment_result'
  get 'process_payment_result', to: 'payments#payment_redirect'
  resources :conversations, only: [:index]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: :true, with: :exception
  before_action :set_locale
  before_action :capture_referal
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_mailer_host, if: :devise_controller?

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
  private
  def capture_referal
    session[:referred_by] = params[:ref] if params[:ref]
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:referred_by])
  end
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  def self.default_url_options(options={})
    options.merge({ :locale => I18n.locale })
  end
  def after_sign_in_path_for(resource)
    if request.subdomain == "ico"
      request.env['omniauth.origin'] || stored_location_for(resource) || ico_account_path(:locale => I18n.locale)
    else
      request.env['omniauth.origin'] || stored_location_for(resource) || new_profile_path(:locale => I18n.locale)
    end
  end
  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      signed_in_root_path(resource)
    else
      if request.subdomain == "ico"
        ico_sign_in_path(resource_name)
      else
        root_path
      end
    end
  end
  def set_mailer_host
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
    Devise::Mailer.default_url_options[:locale] = I18n.locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def ref_link
    ref = 'https://ico.ratedate.net/?ref='+current_ico_user.id.to_s
    ref.html_safe
  end
  def meta_tags
    tags = '<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">'
    tags.html_safe
  end
  def google_analytics
    ga = "<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src='https://www.googletagmanager.com/gtag/js?id=UA-107749703-1'></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-107749703-1');
</script>"
    ga.html_safe
  end
  def ya_metric
    ym="<!-- Yandex.Metrika counter -->
<script type=\"text/javascript\" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter46261626 = new Ya.Metrika({
                    id:46261626,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName(\"script\")[0],
            s = d.createElement(\"script\"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = \"text/javascript\";
        s.async = true;
        s.src = \"https://mc.yandex.ru/metrika/watch.js\";

        if (w.opera == \"[object Opera]\") {
            d.addEventListener(\"DOMContentLoaded\", f, false);
        } else { f(); }
    })(document, window, \"yandex_metrika_callbacks\");
</script>
<noscript><div><img src=\"https://mc.yandex.ru/watch/46261626\" style=\"position:absolute; left:-9999px;\" alt=\"\" /></div></noscript>
<!-- /Yandex.Metrika counter -->"
    ym.html_safe
  end
  def locale_link(is_mobile)
    tr = '<span class="trigger-left">EN</span><span class="trigger-right">RU</span>'
    html_class = 'btn-link trigger'
    if is_mobile
      html_class += ' mobile'
    end
    if I18n.locale==:ru
      link_to({locale: :en}, html_options= {class: html_class+" active"}) do
        tr.html_safe
      end
    else
      link_to({locale: :ru}, html_options={class: html_class}) do
        tr.html_safe
      end
    end
  end
  def wp_link(html_class)
    if I18n.locale==:ru
      link_to "White Paper", "/assets/white_paper_ru_4_0.pdf", {class: html_class, target: "_blank"}
    else
      link_to "White Paper", "/assets/white_paper_en_4_0.pdf", {class: html_class, target: "_blank"}
    end
  end

  # helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def online_status(user)
    content_tag :span, '',
                class: "user-#{user.id} online-status #{'online' if user.online?}"
  end

  def user_avatar
    if current_user.profile.present?
      if current_user.profile.avatar.small_avatar.file.present?
        image_tag current_user.profile.avatar.url(:small_avatar), class: 'rounded-circle', id: 'signed-user'
      else
        image_tag "small_avatar_placeholder.png", class: 'rounded-circle', id: 'signed-user'
      end
    else
      image_tag "small_avatar_placeholder.png", class: 'rounded-circle', id: 'signed-user'
    end
  end

  def etz_raised
    number_with_precision(EtzInvestment.sum(:etz), :precision => 4)
  end
  def languages_list(languages)
    tmp = []
    languages.each{|l| tmp<<language(l)}
    tmp.join(', ')
  end

  def show_timezone
    timezone = 'UTC'
    if current_user
      if current_user.profile
        if current_user.profile.timezone
          timezone = current_user.profile.timezone
        end
      end
    end
    timezone
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/images/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/images/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/images/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/images/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="/assets/images/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/images/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/assets/images/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/images/apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="/assets/images/favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="/assets/images/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="/assets/images/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/assets/images/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="/assets/images/favicon-128.png" sizes="128x128" />
<meta name="application-name" content="Rate Date"/>
<meta name="msapplication-TileColor" content="#9f00a7" />
<meta name="msapplication-TileImage" content="/assets/images/mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="/assets/images/mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="/assets/images/mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="/assets/images/mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="/assets/images/mstile-310x310.png" />

app/views/application/_footer.html.erb
<div class="bg-secondary fixed-bottom container-fluid py-2">
  <div class="row justify-content-center pt-3 text-white">
    <div class="col-md-2"><i class="icon-logo h1 text-light"></i></div>
    <div class="col-md-3 text-center">
      <%= link_to 'Terms of Use', terms_of_use_path, class: 'text-white' %><br>
      <%= link_to 'Privacy Policy', privacy_policy_path, class: 'text-white' %>
    </div>
    <div class="col-md-3 text-center">Copyright © Rate Date<br>info@ratedate.net<br>
      <a href="/assets/Rate Date ICO PRIVACY POLICY.pdf" target="_blank">Privacy Policy</a>
    </div>
    <div class="col-md-4 text-right">
      <div>Follow Us:</div>
      <div class="nav justify-content-end">
        <a href="https://www.facebook.com/Rate-Date-861947790626663/" class="icon-facebook h4 nav-link text-light" target="_blank"></a>
        <a href="https://twitter.com/RateDate2" class="icon-twitter h4 nav-link text-light" target="_blank"></a>
        <a href="https://t.me/icoratedate" class="icon-telegram h4 nav-link text-light" target="_blank"></a>
        <a href="https://medium.com/@usatenko.katerina" class="icon-medium h4 nav-link text-light" target="_blank"></a>
        <a href="https://github.com/ratedate/ratedate" class="icon-github h4 nav-link text-light" target="_blank"></a>
      </div>
    </div>
  </div>
</div>

app/views/application/_rd_main_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-secondary fixed-top">
  <a class="navbar-brand" href="https://ratedate.net/">
    <span class="icon-logo display-4"></span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Profiles', profiles_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to '', conversations_path, class: "nav-link icon-envelope" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Profile', my_profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(:sign_out), sign_out_path, method: :delete, class: "nav-link" %>
          </li>
          </ul>
          <%= user_avatar %>
      <% else %>
          <li class="nav-item">
            <%= link_to t(:sign_in), sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(:sign_up), sign_up_path, class: "nav-link" %>
          </li>
          </ul>
      <% end %>
      </div>
</nav>